### ISSUE TITLE
Set up RabbitMQ exchanges and boilerplate code in Java

### ISSUE THREAD

**Issue by xandervedder** [xandervedder/BEP-03#13]
**Description**
Basic set up of the RabbitMQ with some java config.

**Why is this needed**
If there's no RabbitMQ config, it won't work.

**Tasks**
- [ ] Check example repo https://github.com/arothuis-hu/example-jobboard for inspiration
- [ ] Test implementation by sending a message via the RabbitMQ web interface
- [ ] Exclude from JaCoCo
