### ISSUE TITLE
Implement domain classes and unit tests

### ISSUE THREAD

**Issue by xandervedder** [xandervedder/BEP-03#14]
**Description**
Core business logic of the Review micro-service

**Tasks**
- [ ] Add domain classes
- [ ] Add unit tests 
- [ ] Set up Hexagonal skeleton
