### ISSUE TITLE
Set up MongoDB in Review micro-service

### ISSUE THREAD

**Issue by xandervedder** [xandervedder/BEP-03#26]
**Description**
MongoDB usage in Review micro-service

**Why is this needed**
This is needed so we can store reviews in MongoDB

**Tasks**
- [x] ~~Make Custom `ReviewId` (maybe)~~
- [x] Add annotations to `Review`
- [x] Add `ReviewRepository` in correct folder
