### ISSUE TITLE
Add retrieve product functionality

### ISSUE THREAD

**Issue by Rubenvdbrink** [xandervedder/BEP-03#29]
**Description**
With this service a product's information can be retrieved.

**Why is this needed**
A description of why this is needed.

**Tasks**
- [ ] Implement main functionality
- [ ] Implement database functionality
- [ ] Implement RabbitMQ functionality
