### ISSUE TITLE
Add README.md to Review micro-service

### ISSUE THREAD

**Issue by xandervedder** [xandervedder/BEP-03#40]
**Description**
A README.md with a description of the micro-service and more.

**Why is this needed**
It makes it clear what the purpose is of this micro-service.

**Tasks**
- [x] ~~Write about functionality (documentation)~~ will do this in a different issue
- [x] Write about events (see #46 for more info):
  - [x] Consuming
  - [x] Producing 
- [x] Sonarcloud quality gate icon
