### ISSUE TITLE
Discuss which events the micro-services consume and produce

### ISSUE THREAD

**Issue by xandervedder** [xandervedder/BEP-03#46]
**Description**
We should know this, so we can anticipate what the micro-service consumes and produces.

**Tasks**
- [x] List all events for each micro-service (this should eventually go in the README.md)
- [ ] Discuss routing keys for RabbitMQ
- [x] Discuss exchanges for RabbitMQ

**Comment by xandervedder** [comment]
As for the Review micro-service, I was thinking of the following events:
## Produces
— (not sure about what events it could produce and who would be interested in what)
## Consumes
- CreateReviewEvent (Review/Delivery)
- EditReviewEvent (Review/Delivery)
- DeleteReviewEvent (Review/Delivery)
## REST
I thought about REST for a bit, this is what I came up with:
- Get for specific reviews
- Get for all reviews of a Customer
- Get for all reviews of a certain Product
- Get for all reviews of a delivery man (maybe, I am not sure if that's possible to do)

**Comment by JustMilan** [comment]
As for the Review micro-service, I was thinking of the following events:

## Produces
- deleteReviewFromCustomer()

## Consumes
- createCustomer()
- addReviewToCustomer()
- addOrderToCustomer()

## REST
getReviewsFromCustomer()
getOrdersFromCustomer()

**Comment by xandervedder** [comment]
![image](https://user-images.githubusercontent.com/34238405/146011316-edbf97c9-feeb-4ba5-ba56-f0cc3af10c81.png)

**Comment by JortWillemsen** [comment]
## Produces
- OrderDeleted
- ItemAddedToOrder
- OrderCreated
- OrderStatusChanged (optional)

## Consumes
- DeleteOrder
- AddItemToOrder
- CreateOrder
- UpdateOrderStatus (optional)

## REST
- GetOrdersByCustomer
- GetCurrentOrdersByCustomer
- GetAllOrders
- GetOrderSummary
- GetOrderPrice

**Comment by Rubenvdbrink** [comment]
### Produces
ProductDeleted
ProductAdded
ProductInformationChanged

### Consumes
AddReview (maybe) @xandervedder ?
DeleteReview (maybe) @xandervedder ?
### REST

GetAllProduct
GetProductById

**Comment by arjennorbart** [comment]
# Delivery micro-service

## Produces
- DeliveryStatusChanged
- DeliveryRegistered
- DeliveryAddressChanged

## Consumes
- ChangeDeliveryStatus
- RegisterDelivery
- ChangeDeliveryAddress

## REST
- GetDeliveryStatus
- GetAllDeliveries
- GetDeliveryByOrder
