### ISSUE TITLE
Add stock implementation for product and order service.

### ISSUE THREAD

**Issue by Rubenvdbrink** [xandervedder/BEP-03#89]
**Description**
When a product gets added to an order the stock of the product should be reduced by one(or more depending on how big of a quantity is added). Order should produce an event where Product listens to. 

**Why is this needed**
It's not

**Tasks**
- [ ] Add listening queue in product microservice to the produced event by Order
- [ ] Add stock field to Product
- [ ] Add published event to the order microservice
